import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import { format, parse } from 'date-fns'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

// Helper to generate HTML email
function generateReportEmailHtml(
  clientName: string,
  month: string,
  postsCount: number,
  gscImpressions: number,
  gscClicks: number,
  gscCtr: number,
  pdfUrl: string,
  primaryColor = '#6d28d9'
): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: sans-serif; max-width: 600px; margin: 0 auto; }
    .header { background: ${primaryColor}; color: white; padding: 30px 20px; text-align: center; }
    .header h1 { margin: 0 0 10px 0; font-size: 28px; }
    .header p { margin: 0; font-size: 16px; opacity: 0.9; }
    .content { padding: 30px 20px; background: #f9fafb; }
    .metrics-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 25px 0; }
    .metric { background: white; padding: 15px; border-radius: 8px; border-left: 4px solid ${primaryColor}; }
    .metric-label { margin: 0 0 8px 0; font-size: 12px; color: #9ca3af; text-transform: uppercase; letter-spacing: 0.5px; }
    .metric-value { margin: 0; font-size: 24px; font-weight: bold; color: #1f2937; }
    .button { display: inline-block; background: ${primaryColor}; color: white; padding: 12px 30px; border-radius: 6px; text-decoration: none; font-weight: bold; font-size: 15px; }
    .footer { background: #f3f4f6; padding: 20px; text-align: center; font-size: 12px; color: #9ca3af; }
    .footer p { margin: 0; }
    .footer-note { font-size: 11px; margin-top: 10px; font-style: italic; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Monthly SEO Report</h1>
    <p>${month}</p>
  </div>
  <div class="content">
    <p style="font-size: 16px; color: #374151; margin-bottom: 20px;">Hi there,</p>
    <p style="font-size: 15px; color: #6b7280; margin-bottom: 25px;">
      Your SEO performance report for <strong>${clientName}</strong> is ready. Here's a quick overview of your progress this month:
    </p>
    <div class="metrics-grid">
      <div class="metric">
        <p class="metric-label">Posts Published</p>
        <p class="metric-value">${postsCount}</p>
      </div>
      <div class="metric">
        <p class="metric-label">Impressions</p>
        <p class="metric-value">${gscImpressions.toLocaleString()}</p>
      </div>
      <div class="metric">
        <p class="metric-label">Clicks</p>
        <p class="metric-value">${gscClicks.toLocaleString()}</p>
      </div>
      <div class="metric">
        <p class="metric-label">CTR</p>
        <p class="metric-value">${(gscCtr * 100).toFixed(2)}%</p>
      </div>
    </div>
    <div style="text-align: center; margin: 25px 0;">
      <a href="${pdfUrl}" class="button">Download Full Report</a>
    </div>
    <p style="font-size: 13px; color: #9ca3af; margin-bottom: 20px;">
      This report includes detailed insights into your search performance, including month-over-month comparisons and performance trends.
    </p>
  </div>
  <div class="footer">
    <p>Report generated by <strong>Bloggy</strong> • ${new Date().toLocaleDateString()}</p>
    <p class="footer-note">Data sourced from Google Search Console.</p>
  </div>
</body>
</html>
  `.trim()
}

/**
 * POST /api/reports/email
 * Send monthly report via email
 *
 * Body:
 *   - clientId: UUID
 *   - month: ISO date string (e.g., "2026-04-01")
 *   - recipientEmail: email to send to (will use primary user email if omitted)
 */
export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { clientId, month, recipientEmail } = await request.json()

  if (!clientId || !month) {
    return NextResponse.json({ error: 'clientId and month required' }, { status: 400 })
  }

  if (!process.env.RESEND_API_KEY) {
    return NextResponse.json({ error: 'Email service not configured' }, { status: 500 })
  }

  try {
    // Get client and report data
    const { data: client, error: clientError } = await supabase
      .from('clients')
      .select('id, name, website, primary_color')
      .eq('id', clientId)
      .single()

    if (clientError || !client) {
      return NextResponse.json({ error: 'Client not found' }, { status: 404 })
    }

    const { data: report, error: reportError } = await supabase
      .from('monthly_reports')
      .select('*')
      .eq('user_id', user.id)
      .eq('client_id', clientId)
      .eq('year_month', month.split('T')[0])
      .single()

    if (reportError || !report) {
      return NextResponse.json({ error: 'Report not found. Generate report first.' }, { status: 404 })
    }

    if (!report.pdf_url) {
      return NextResponse.json({ error: 'PDF not generated yet. Generate PDF first.' }, { status: 400 })
    }

    // Format month for display
    const monthDate = parse(month, 'yyyy-MM-dd', new Date())
    const monthLabel = format(monthDate, 'MMMM yyyy')

    // Generate email HTML
    const htmlString = generateReportEmailHtml(
      client.name,
      monthLabel,
      report.posts_count,
      report.gsc_impressions,
      report.gsc_clicks,
      report.gsc_ctr,
      report.pdf_url,
      client.primary_color || '#6d28d9'
    )

    // Send email
    const toEmail = recipientEmail || user.email
    const { data, error } = await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL || 'reports@bloggy.online',
      to: toEmail,
      subject: `Your SEO Report for ${client.name} — ${monthLabel}`,
      html: htmlString,
    })

    if (error) {
      console.error('Resend error:', error)
      return NextResponse.json({ error: 'Failed to send email', details: error.message }, { status: 500 })
    }

    // Update report record with email sent timestamp
    await supabase
      .from('monthly_reports')
      .update({ email_sent_at: new Date().toISOString() })
      .eq('id', report.id)

    return NextResponse.json({
      success: true,
      messageId: data.id,
      sentTo: toEmail,
    })
  } catch (error) {
    console.error('Email send error:', error)
    return NextResponse.json(
      { error: 'Failed to send email', details: String(error) },
      { status: 500 }
    )
  }
}
