import React from 'react'

interface ReportEmailProps {
  clientName: string
  month: string
  postsCount: number
  gscImpressions: number
  gscClicks: number
  gscCtr: number
  pdfUrl: string
  primaryColor?: string
}

export function ReportEmail({
  clientName,
  month,
  postsCount,
  gscImpressions,
  gscClicks,
  gscCtr,
  pdfUrl,
  primaryColor = '#6d28d9',
}: ReportEmailProps) {
  return (
    <div style={{ fontFamily: 'sans-serif', maxWidth: '600px', margin: '0 auto' }}>
      <div
        style={{
          backgroundColor: primaryColor,
          color: 'white',
          padding: '30px 20px',
          textAlign: 'center',
        }}
      >
        <h1 style={{ margin: '0 0 10px 0', fontSize: '28px' }}>Monthly SEO Report</h1>
        <p style={{ margin: '0', fontSize: '16px', opacity: 0.9 }}>{month}</p>
      </div>

      <div style={{ padding: '30px 20px', backgroundColor: '#f9fafb' }}>
        <p style={{ fontSize: '16px', color: '#374151', marginBottom: '20px' }}>
          Hi there,
        </p>

        <p style={{ fontSize: '15px', color: '#6b7280', marginBottom: '25px' }}>
          Your SEO performance report for <strong>{clientName}</strong> is ready. Here's a quick
          overview of your progress this month:
        </p>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(2, 1fr)',
            gap: '15px',
            marginBottom: '25px',
          }}
        >
          <div
            style={{
              backgroundColor: 'white',
              padding: '15px',
              borderRadius: '8px',
              borderLeft: `4px solid ${primaryColor}`,
            }}
          >
            <p style={{ margin: '0 0 8px 0', fontSize: '12px', color: '#9ca3af' }}>
              POSTS PUBLISHED
            </p>
            <p style={{ margin: '0', fontSize: '24px', fontWeight: 'bold', color: '#1f2937' }}>
              {postsCount}
            </p>
          </div>
          <div
            style={{
              backgroundColor: 'white',
              padding: '15px',
              borderRadius: '8px',
              borderLeft: `4px solid ${primaryColor}`,
            }}
          >
            <p style={{ margin: '0 0 8px 0', fontSize: '12px', color: '#9ca3af' }}>
              IMPRESSIONS
            </p>
            <p style={{ margin: '0', fontSize: '24px', fontWeight: 'bold', color: '#1f2937' }}>
              {gscImpressions.toLocaleString()}
            </p>
          </div>
          <div
            style={{
              backgroundColor: 'white',
              padding: '15px',
              borderRadius: '8px',
              borderLeft: `4px solid ${primaryColor}`,
            }}
          >
            <p style={{ margin: '0 0 8px 0', fontSize: '12px', color: '#9ca3af' }}>CLICKS</p>
            <p style={{ margin: '0', fontSize: '24px', fontWeight: 'bold', color: '#1f2937' }}>
              {gscClicks.toLocaleString()}
            </p>
          </div>
          <div
            style={{
              backgroundColor: 'white',
              padding: '15px',
              borderRadius: '8px',
              borderLeft: `4px solid ${primaryColor}`,
            }}
          >
            <p style={{ margin: '0 0 8px 0', fontSize: '12px', color: '#9ca3af' }}>CTR</p>
            <p style={{ margin: '0', fontSize: '24px', fontWeight: 'bold', color: '#1f2937' }}>
              {(gscCtr * 100).toFixed(2)}%
            </p>
          </div>
        </div>

        <div style={{ textAlign: 'center', marginBottom: '25px' }}>
          <a
            href={pdfUrl}
            style={{
              display: 'inline-block',
              backgroundColor: primaryColor,
              color: 'white',
              padding: '12px 30px',
              borderRadius: '6px',
              textDecoration: 'none',
              fontWeight: 'bold',
              fontSize: '15px',
            }}
          >
            Download Full Report
          </a>
        </div>

        <p style={{ fontSize: '13px', color: '#9ca3af', marginBottom: '20px' }}>
          This report includes detailed insights into your search performance, including
          month-over-month comparisons and performance trends.
        </p>
      </div>

      <div
        style={{
          backgroundColor: '#f3f4f6',
          padding: '20px',
          textAlign: 'center',
          fontSize: '12px',
          color: '#9ca3af',
        }}
      >
        <p style={{ margin: '0 0 10px 0' }}>
          Report generated by <strong>Bloggy</strong> • {new Date().toLocaleDateString()}
        </p>
        <p style={{ margin: '0', fontSize: '11px' }}>
          Data sourced from Google Search Console.
        </p>
      </div>
    </div>
  )
}
